engines:
 rubocop:
   enabled: true
 duplication:
   enabled: true
 metrics:
   enabled: true
 coverage:
   enabled: true

exclude_paths:
  - '*.spec.ts'
  - '**/__tests__/**'
  - 'ios/**/*'
  - 'android/**/*'
  - 'e2e/**/*'
  - 'e2e/*'
  - 'jest.config.js'
