export const GET_DEBTS_BY_CONTACT_FETCHED =
  'Contacts/GET_DEBTS_BY_CONTACT_FETCHED';
export const GET_DEBTS_BY_CONTACT_SUCCESS =
  'Contacts/GET_DEBTS_BY_CONTACT_SUCCESS';
export const GET_DEBTS_BY_CONTACT_FAILED =
  'Contacts/GET_DEBTS_BY_CONTACT_FAILED';
