export const GET_CALLS_BY_CONTACT_FETCHED =
  'Contacts/GET_CALLS_BY_CONTACT_FETCHED';
export const GET_CALLS_BY_CONTACT_SUCCESS =
  'Contacts/GET_CALLS_BY_CONTACT_SUCCESS';
export const GET_CALLS_BY_CONTACT_FAILED =
  'Contacts/GET_CALLS_BY_CONTACT_FAILED';
