# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
     match(
      type: "appstore",
      git_url: "git@gitlab.com:monicahq/mobile-creds.git"
    )
    increment_build_number(xcodeproj: "Monica.xcodeproj")
    build_app(workspace: "Monica.xcworkspace", scheme: "Monica")
    upload_to_testflight
    notification(subtitle: "Finished uploading", message: "Testflight has accepted the build.")
  end


  lane :certificates do
    register_devices(devices_file: "./devices.txt")
    match(git_url: "git@gitlab.com:monicahq/mobile-creds.git", type: "adhoc", force_for_new_devices: true)
    match(git_url: "git@gitlab.com:monicahq/mobile-creds.git", type: "development", force_for_new_devices: true, app_identifier: "com.monicahq.app.debug")
  end

  lane :version do |options|
    increment_version_number(
      version_number: options[:version]
    )
  end
end
