# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Submit a new Alpha Build to Android Play store"
  lane :alpha do
    increment_version_code
    gradle(task: "assembleRelease")

    supply(
      track: "alpha",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
  end

  desc "Submit a new Beta Build to Android Play store"
  lane :beta do
    increment_version_code
    gradle(task: "assembleRelease")

    supply(
      track: "beta",
      apk: "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    )
  end

  lane :version do |options|
    android_set_version_name(
      version_name: options[:version],
    )
  end
end
