export const GET_GIFTS_BY_CONTACT_FETCHED =
  'Contacts/GET_GIFTS_BY_CONTACT_FETCHED';
export const GET_GIFTS_BY_CONTACT_SUCCESS =
  'Contacts/GET_GIFTS_BY_CONTACT_SUCCESS';
export const GET_GIFTS_BY_CONTACT_FAILED =
  'Contacts/GET_GIFTS_BY_CONTACT_FAILED';
